---
- name: Configlet upload management
  hosts: DC-FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:

    - name: 'generate intended configuration'
      import_role:
        name: arista.avd.eos_cli_config_gen

- name: Configlet upload configlets
  hosts: CV-SERVER
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:
    - name: 'upload configlets to cloudvision {{inventory_hostname}}'
      tags: [never, apply]
      import_role:
        name: arista.avd.cvp_configlet_upload
      vars:
        configlet_directory: './inventory/intended/configs'
        configlets_cvp_prefix: 'ANSIBLE'
        file_extension: 'cfg'

    - name: "Configure devices on {{inventory_hostname}}"
      tags: [never, apply]
      arista.cvp.cv_device_v3:
        devices: "{{CVP_DEVICES}}"
        state: present
      register: cvp_device_results

    - name: show task IDs in the terminal ouput
      tags: [never, apply]
      debug:
        msg: "{{ cvp_device_results.taskIds }}"

#    - name: Execute all tasks registered in cvp_configlets variable
#      tags: [never, apply]
#      arista.cvp.cv_task:
#        tasks: "{{ cvp_device_results.taskIds }}"

