---
- name: Configlet upload management
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd

  tasks:
    - name: generate intended variables
      tags: [always]
      inventory_to_container:
        inventory: "./inventory/inventory.yml"
        container_root: "DC"
        configlet_dir: "./inventory/intended/configs"
        configlet_prefix: "ANSIBLE"
        destination: "./inventory/intended/structured_configs/{{inventory_hostname}}.yml"