---
# Play to build EOS configuration from EOS_DESIGNS
- hosts: DC_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:

    # BUILD EOS configuration
    - name: generate intended variables
      import_role:
         name: eos_designs
    - name: generate device intended config and documentation
      import_role:
         name: eos_cli_config_gen