---
- name: CVP gather facts
  hosts: CVP
  connection: httpapi
  gather_facts: no
  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
        facts:
          devices 
#        gather_subset:
#          hardware
      register: cv_facts

    - name: "Print out facts from {{inventory_hostname}}"
      debug:
#        msg: "{{cv_facts.ansible_facts.devices | map(attribute='hostname') | to_nice_json(indent=2)}}"
#        msg: "Single_Device: {{cv_facts.ansible_facts | to_nice_json(indent=3)}}"
        msg: 
        - "Device hostname is {{item.hostname}}"
        - "IP: {{item.ipAddress}}"
        - "Version: {{item.version}}"
        - "Container: {{item.containerName}}"
        - "Assigned Configlets: {{item.deviceSpecificConfiglets | list}}"
      loop: "{{cv_facts.ansible_facts.devices}}"
      loop_control:
        label: ""